### PR TITLE
Refactor to sommelier-core

### PR DESCRIPTION
**Pull request by galgalesh**
This PR refactors the snap to use sommelier-core. See [the announcement](https://forum.snapcraft.io/t/call-for-testing-snap-windows-apps-with-sommelier-core/18728) for more details.

This should fix a bunch of issues, greatly reduce the size of the snap and make it much easier to maintain.

I was not able to get the original snap going on Ubuntu 20.04, but the version from this PR works flawlessly. I suspect the switch to core18 and the new desktop-helpers from the `gnome-3-28` extension has solved a lot of issues.

I was not able to do an FPS comparison with the previous version of the snap because I could not get it to work. However, I get better FPS with this snap than when I install tmnationsforever using PlayOnLinux.

### CODE REVIEW

**Comment by galgalesh** [comment]
@flexiondotorg are you the right person to ping about this?

**Comment by popey** [comment]
Sorry for the delay, I'll take a look at this over the weekend! Thanks!

**Comment by galgalesh** [comment]
Thanks! I know it's a big change at once ;)

I just updated the PR to re-add i386 support and to use wine virtual desktop again. (this now works on Wayland too!)

**Comment by xordspar0** [comment]
I tested this out and it works great. Thanks for your work on sommelier-core. It's a huge improvement. Let's get this merged!

**Pull request merged**
